// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
// 在main.c的全局变量区域添加
extern lv_obj_t *ui_Label2;  // 声明外部变量，指向"微笑"标签

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    
    // 设置屏幕背景为黑色
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    //yf
    lv_obj_set_width(ui_Screen1, 0);
    //yf
    
    ui_Image2 = lv_img_create(ui_Screen1);
    lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    // 移除 ui_Panel1，直接在 ui_Screen1 上创建控件

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Label1, -281 );
    lv_obj_set_y( ui_Label1, -219 );
    lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label1,"7月23日");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Label3, -210 );
    lv_obj_set_y( ui_Label3, -219 );
    lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label3,"星期三");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

    // 移除 ui_Panel2，直接在 ui_Screen1 上创建控件

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width( ui_Label2, 600);  /// 设置固定宽度，为自动换行做准备
    lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 高度自适应内容
    lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label2,"通过触摸左镜腿进入菜单 ");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_alibaba_48, LV_PART_MAIN| LV_STATE_DEFAULT);

    // 设置自动换行模式
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_WRAP);  // 自动换行
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);  // 文本居中对齐

    // 设置行间距（使用正确的函数名）
    lv_obj_set_style_text_line_space(ui_Label2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加这一行：创建后立即隐藏
    //lv_obj_add_flag(ui_Label2, LV_OBJ_FLAG_HIDDEN);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_799793925);
    lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Image3, 176 );
    lv_obj_set_y( ui_Image3, -223 );
    lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Label4, 197 );
    lv_obj_set_y( ui_Label4, -223 );
    lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label4,"101");

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_lanya_png);
    lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Image4, 218 );
    lv_obj_set_y( ui_Image4, -223 );
    lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width( ui_Slider1, 42);
    lv_obj_set_height( ui_Slider1, 10);
    lv_obj_set_x( ui_Slider1, 279 );
    lv_obj_set_y( ui_Slider1, -223 );
    lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFB8F03), LV_PART_INDICATOR | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_Label5, 242 );
    lv_obj_set_y( ui_Label5, -223 );
    lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label5,"99%");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFB8F03), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    // 创建对话气泡
    // 主气泡（圆角矩形）
    ui_SpeechBubble = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SpeechBubble, 103);
    lv_obj_set_height(ui_SpeechBubble, 81);
    lv_obj_set_x(ui_SpeechBubble, 0);
    lv_obj_set_y(ui_SpeechBubble, -80);  // 向上移动80像素
    lv_obj_set_align(ui_SpeechBubble, LV_ALIGN_CENTER);
    
    // 设置圆角矩形样式
    lv_obj_set_style_radius(ui_SpeechBubble, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeechBubble, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeechBubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SpeechBubble, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeechBubble, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeechBubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 移除默认的滚动标志
    lv_obj_clear_flag(ui_SpeechBubble, LV_OBJ_FLAG_SCROLLABLE);
    
    // 创建后立即隐藏对话气泡
    lv_obj_add_flag(ui_SpeechBubble, LV_OBJ_FLAG_HIDDEN);
    
    // 创建右下角的两条直线来形成对话气泡的尾巴
    // 第一条直线（垂直向下）
    ui_SpeechTail1 = lv_line_create(ui_Screen1);
    static lv_point_t tail1_points[] = {{0, 0}, {0, 20}};
    lv_line_set_points(ui_SpeechTail1, tail1_points, 2);
    lv_obj_set_x(ui_SpeechTail1, 350);   // 从气泡右边缘开始 (320 + 103/2)
    lv_obj_set_y(ui_SpeechTail1, 200);   // 从气泡底部开始 (280 - 80 = 200)
    lv_obj_set_style_line_width(ui_SpeechTail1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_SpeechTail1, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_SpeechTail1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第一条尾巴
    lv_obj_add_flag(ui_SpeechTail1, LV_OBJ_FLAG_HIDDEN);
    
    // 第二条直线（斜向右下）
    ui_SpeechTail2 = lv_line_create(ui_Screen1);
    static lv_point_t tail2_points[] = {{0, 0}, {20, 20}};
    lv_line_set_points(ui_SpeechTail2, tail2_points, 2);
    lv_obj_set_x(ui_SpeechTail2, 330);   // 从第一条直线的末端开始
    lv_obj_set_y(ui_SpeechTail2, 200);   // 从第一条直线的末端开始 (280 - 80 = 200)
    lv_obj_set_style_line_width(ui_SpeechTail2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_SpeechTail2, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_SpeechTail2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第二条尾巴
    lv_obj_add_flag(ui_SpeechTail2, LV_OBJ_FLAG_HIDDEN);
//


//录像机的图标，但是没测试

//
    // 创建圆形，中心位置与圆角矩形相同，直径51像素
    ui_Circle = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Circle, 51);
    lv_obj_set_height(ui_Circle, 51);
    lv_obj_set_x(ui_Circle, 0);
    lv_obj_set_y(ui_Circle, -80);  // 与圆角矩形相同的Y位置
    lv_obj_set_align(ui_Circle, LV_ALIGN_CENTER);
    
    // 设置圆形样式
    lv_obj_set_style_radius(ui_Circle, 25, LV_PART_MAIN | LV_STATE_DEFAULT);  // 半径25像素，形成直径51像素的圆
    lv_obj_set_style_bg_color(ui_Circle, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 黑色背景
    lv_obj_set_style_bg_opa(ui_Circle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框作为本体，增加到4像素
    lv_obj_set_style_border_color(ui_Circle, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框
    lv_obj_set_style_border_opa(ui_Circle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 移除默认的滚动标志
    lv_obj_clear_flag(ui_Circle, LV_OBJ_FLAG_SCROLLABLE);
    
    // 创建后立即隐藏圆形
    lv_obj_add_flag(ui_Circle, LV_OBJ_FLAG_HIDDEN);

    // 创建圆形上方的竖线，距离圆形7像素，长度7像素
    ui_UpperLine = lv_line_create(ui_Screen1);
    static lv_point_t upper_line_points[] = {{0, 0}, {0, 7}};
    lv_line_set_points(ui_UpperLine, upper_line_points, 2);
    lv_obj_set_x(ui_UpperLine, 322);  // 绝对坐标：屏幕中心X (640/2)
    lv_obj_set_y(ui_UpperLine, 113);  // 绝对坐标：圆形中心Y (240) - 7距离 - 7长度 = 226
    // 移除居中对齐，使用绝对坐标
    lv_obj_set_style_line_width(ui_UpperLine, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_UpperLine, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_UpperLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏上方竖线
    lv_obj_add_flag(ui_UpperLine, LV_OBJ_FLAG_HIDDEN);
    
    // 创建圆形下方的竖线，距离圆形7像素，长度7像素
    ui_LowerLine = lv_line_create(ui_Screen1);
    static lv_point_t lower_line_points[] = {{0, 0}, {0, 7}};
    lv_line_set_points(ui_LowerLine, lower_line_points, 2);
    lv_obj_set_x(ui_LowerLine, 2);
    lv_obj_set_y(ui_LowerLine, -44);  // 圆形Y位置(-80) + 圆形半径(25.5) + 7像素距离 = -66
    lv_obj_set_align(ui_LowerLine, LV_ALIGN_CENTER);
    lv_obj_set_style_line_width(ui_LowerLine, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_LowerLine, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_LowerLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏下方竖线
    lv_obj_add_flag(ui_LowerLine, LV_OBJ_FLAG_HIDDEN);

    // 创建圆形左侧的横线，距离圆形7像素，长度7像素
    ui_LeftLine = lv_line_create(ui_Screen1);
    static lv_point_t left_line_points[] = {{0, 0}, {7, 0}};
    lv_line_set_points(ui_LeftLine, left_line_points, 2);
    lv_obj_set_x(ui_LeftLine, -32);  // 圆形X位置(0) - 圆形半径(25.5) - 7像素距离 = -32
    lv_obj_set_y(ui_LeftLine, -80);  // 与圆形中心Y位置相同
    lv_obj_set_align(ui_LeftLine, LV_ALIGN_CENTER);
    lv_obj_set_style_line_width(ui_LeftLine, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_LeftLine, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_LeftLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏左侧横线
    lv_obj_add_flag(ui_LeftLine, LV_OBJ_FLAG_HIDDEN);
    
    // 创建圆形右侧的横线，距离圆形7像素，长度7像素
    ui_RightLine = lv_line_create(ui_Screen1);
    static lv_point_t right_line_points[] = {{0, 0}, {7, 0}};
    lv_line_set_points(ui_RightLine, right_line_points, 2);
    lv_obj_set_x(ui_RightLine, 352);   // 圆形X位置(0) + 圆形半径(25.5) + 7像素距离 = 32
    lv_obj_set_y(ui_RightLine, 160);  // 与圆形中心Y位置相同
    lv_obj_set_style_line_width(ui_RightLine, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_RightLine, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_RightLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏右侧横线
    lv_obj_add_flag(ui_RightLine, LV_OBJ_FLAG_HIDDEN);

    // 创建录像机图标
    // 右边的80×80圆角矩形，向右偏移21像素
    ui_VideoRecorderRect = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_VideoRecorderRect, 80);
    lv_obj_set_height(ui_VideoRecorderRect, 80);
    lv_obj_set_x(ui_VideoRecorderRect, 13);  // 向右偏移13像素（21-8=13）
    lv_obj_set_y(ui_VideoRecorderRect, -80);  // 向上移动80像素
    lv_obj_set_align(ui_VideoRecorderRect, LV_ALIGN_CENTER);
    
    // 设置圆角矩形样式
    lv_obj_set_style_radius(ui_VideoRecorderRect, 12, LV_PART_MAIN | LV_STATE_DEFAULT);  // 增大圆角到12像素
    lv_obj_set_style_bg_color(ui_VideoRecorderRect, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 黑色背景（空心效果）
    lv_obj_set_style_bg_opa(ui_VideoRecorderRect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // 背景透明（空心效果）
    lv_obj_set_style_border_width(ui_VideoRecorderRect, 4, LV_PART_MAIN | LV_STATE_DEFAULT);  // 4像素边框
    lv_obj_set_style_border_color(ui_VideoRecorderRect, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框
    lv_obj_set_style_border_opa(ui_VideoRecorderRect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);  // 边框不透明
    
    // 移除默认的滚动标志
    lv_obj_clear_flag(ui_VideoRecorderRect, LV_OBJ_FLAG_SCROLLABLE);
    
    // 创建后立即隐藏录像机矩形
    lv_obj_add_flag(ui_VideoRecorderRect, LV_OBJ_FLAG_HIDDEN);
    
    // 左边的三条线组成录像机图标
    // 第一条：竖线 267,137 到 267,183
    ui_VideoLine1 = lv_line_create(ui_Screen1);
    static lv_point_t video_line1_points[] = {{267, 137}, {267, 183}};
    lv_line_set_points(ui_VideoLine1, video_line1_points, 2);
    lv_obj_set_x(ui_VideoLine1, 0);
    lv_obj_set_y(ui_VideoLine1, 0);
    lv_obj_set_style_line_width(ui_VideoLine1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_VideoLine1, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_VideoLine1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第一条线
    lv_obj_add_flag(ui_VideoLine1, LV_OBJ_FLAG_HIDDEN);
    
    // 第二条：斜线 267,137 到 293,151
    ui_VideoLine2 = lv_line_create(ui_Screen1);
    static lv_point_t video_line2_points[] = {{267, 137}, {293, 151}};
    lv_line_set_points(ui_VideoLine2, video_line2_points, 2);
    lv_obj_set_x(ui_VideoLine2, 0);
    lv_obj_set_y(ui_VideoLine2, 0);
    lv_obj_set_style_line_width(ui_VideoLine2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_VideoLine2, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_VideoLine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第二条线
    lv_obj_add_flag(ui_VideoLine2, LV_OBJ_FLAG_HIDDEN);
    
    // 第三条：斜线 267,183 到 293,174
    ui_VideoLine3 = lv_line_create(ui_Screen1);
    static lv_point_t video_line3_points[] = {{267, 183}, {293, 174}};
    lv_line_set_points(ui_VideoLine3, video_line3_points, 2);
    lv_obj_set_x(ui_VideoLine3, 0);
    lv_obj_set_y(ui_VideoLine3, 0);
    lv_obj_set_style_line_width(ui_VideoLine3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_VideoLine3, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_VideoLine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第三条线
    lv_obj_add_flag(ui_VideoLine3, LV_OBJ_FLAG_HIDDEN);

}
